/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/5mjAEvkScR1
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel"
import { Label } from "@/components/ui/label"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import { JSX, SVGProps,useState,useEffect, SetStateAction } from "react"
import { getCart } from "@/app/actions"
import { useToast } from "@/components/ui/use-toast"
import ProductNotFound from "@/components/component/product-not-found"
export function ProductDescription ({ product,sessionId }: { product: { id: number, picture1: string, picture2: string, picture3: string ,  title: string, description: string, price: number, anime:string } ;sessionId: string }) {
  if (!product) {
    return <ProductNotFound/>
  }
  if (product.title === '') {
    return <ProductNotFound/>
  }
  const [cartId, setCartId] = useState(0);
  const [selectedQuantity, setSelectedQuantity] = useState(1);

  // Handle the change event to update the selected quantity
  const handleQuantityChange = (value: string) => {
    setSelectedQuantity(Number(value));
  };
  useEffect(() => {
    // Fetch cart data when the component mounts
    const fetchCart = async () => {
      try {
        const cart1 = await getCart(sessionId);
        if (cart1 && cart1.length > 0) {
          const cartId = cart1[0].id;
          console.log("cartId", cartId);
          setCartId(cartId);
        }
      } catch (error) {
        console.error("Error fetching cart:", error);
      }
    };

    fetchCart();
  }, [sessionId]);
  const { toast } = useToast()
  const handleCreate = async () => {
    const res = await fetch("/api/cartItem", {
      method: "POST",
      
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        productId: product.id,
        quantity:Number(selectedQuantity),
        cartId: cartId,
      }),
    });
    if (res.ok) {
      console.log("Item added to cart");
      toast({
        title: "Item Added to Cart succesfully",
      })
    } else {
      console.error("Failed to add item to cart");
      toast({
        title: "Item Already in",
      })
    }
  }
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    handleCreate();
  };
  return (
    <div className="grid md:grid-cols-2 gap-6 lg:gap-12 items-start max-w-6xl px-4 mx-auto py-6">
      <div className="grid gap-4 md:gap-8">
        <Carousel className="w-full max-w-md">
          <CarouselContent>
            <CarouselItem>
              <div className="relative group">
                <img
                  src={product.picture1}
                  width={600}
                  height={600}
                  alt="Product Image"
                  className="aspect-square object-cover w-full rounded-lg overflow-hidden group-hover:scale-110 transition-transform"
                />
              </div>
            </CarouselItem>
            <CarouselItem>
              <div className="relative group">
                <img
                  src={product.picture2}
                  width={600}
                  height={600}
                  alt="Product Image"
                  className="aspect-square object-cover w-full rounded-lg overflow-hidden group-hover:scale-110 transition-transform"
                />
                
              </div>
            </CarouselItem>
            <CarouselItem>
              <div className="relative group">
                <img
                  src={product.picture3}
                  width={600}
                  height={600}
                  alt="Product Image"
                  className="aspect-square object-cover w-full rounded-lg overflow-hidden group-hover:scale-110 transition-transform"
                />
              </div>
            </CarouselItem>
          </CarouselContent>
          <CarouselPrevious />
          <CarouselNext />
        </Carousel>
      </div>
      <div className="grid gap-4 md:gap-10 items-start">
        <div className="grid gap-2">
          <h1 className="font-bold text-3xl lg:text-4xl">{product.title}</h1>
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-0.5">
              <StarIcon className="w-5 h-5 fill-primary" />
              <StarIcon className="w-5 h-5 fill-primary" />
              <StarIcon className="w-5 h-5 fill-primary" />
              <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
              <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
            </div>
            <div className="text-4xl font-bold">{product.price} DZD</div>
          </div>
          <div>
            <p><b>{product.anime}</b></p>
          </div>
          <div>
            <p>{product.description}</p>
          </div>
        </div>
        <form className="grid gap-4 md:gap-10">
          <div className="grid gap-2">
            <Label htmlFor="quantity" className="text-base">
              Quantity
            </Label>
            <Select value={selectedQuantity.toString()} onValueChange={handleQuantityChange}>
              <SelectTrigger className="w-24">
                <SelectValue placeholder="Select" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="1">1</SelectItem>
                <SelectItem value="2">2</SelectItem>
                <SelectItem value="3">3</SelectItem>
                <SelectItem value="4">4</SelectItem>
                <SelectItem value="5">5</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <Button size="lg" onClick={handleSubmit} >Add to cart</Button>
        </form>
      </div>
    </div>
  )
}

function StarIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}

