/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/b0OEhPBL9ri
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardContent } from "@/components/ui/card"
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function ProductCardC({img, title, description, price ,className,id}: {img: string, title: string, description: string, price: number,className:string,id:Number}) {
  return (
    <Card className={`w-72 max-w-sm overflow-hidden rounded-lg shadow-lg transition-all hover:scale-[1.02] hover:shadow-xl ${className} `}>
      <Link href={`/product/${id}`} className="block" >
        <img
          src={img}
          alt="Product Image"
         
          className="h-[300px] w-full "
        />
      </Link>
      <CardContent className="p-4">
        <div className="mb-2">
          <Link href={`/product/${id}`} className="block" prefetch={false}>
            <h3 className="text-lg font-bold text-black">{title}</h3>
          </Link>
          <p className="text-sm text-muted-foreground">
            {description}
          </p>
        </div>
        <div className="flex items-center justify-between">
          <span className="text-2xl font-bold text-primary">{price}DZD</span>
          <Button variant="outline" size="sm">
            Add to Cart
          </Button>
        </div>
      </CardContent>
    </Card>
  )
}
