/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/8Mr6N6rpUxZ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { DM_Sans } from 'next/font/google'
import { Rethink_Sans } from 'next/font/google'

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { deleteProduct } from "@/app/actions"
export function ProductsTable(products) {
  const handleDelete = (id) => {
    console.log(id)
    deleteProduct(id)
  }
  // const [products, setProducts] = useState([
  //   {
  //     id: 1,
  //     name: "Gamer Gear Pro Controller",
  //     description: "High-performance gaming controller",
  //     price: 59.99,
  //     stock: 100,
  //   },
  //   {
  //     id: 2,
  //     name: "Luminous VR Headset",
  //     description: "Immersive virtual reality experience",
  //     price: 199.99,
  //     stock: 50,
  //   },
  //   {
  //     id: 3,
  //     name: "Aqua Filters",
  //     description: "Advanced water filtration system",
  //     price: 29.99,
  //     stock: 75,
  //   },
  //   {
  //     id: 4,
  //     name: "Eco Planters",
  //     description: "Sustainable indoor gardening",
  //     price: 39.99,
  //     stock: 25,
  //   },
  //   {
  //     id: 5,
  //     name: "Zest Juicers",
  //     description: "Powerful juicing machine",
  //     price: 99.99,
  //     stock: 150,
  //   },
  // ])
  console.log(products)
  const [sortColumn, setSortColumn] = useState("name")
  const [sortDirection, setSortDirection] = useState("asc")
  const [filterText, setFilterText] = useState("")
  const handleSort = (column) => {
    if (sortColumn === column) {
      setSortDirection(sortDirection === "asc" ? "desc" : "asc");
    } else {
      setSortColumn(column);
      setSortDirection("asc");
    }
  };

  const handleFilter = (e) => {
    setFilterText(e.target.value);
  };

  const filteredProducts = Array.isArray(products.products) ? products.products.filter(
    (product) =>
      product.name.toLowerCase().includes(filterText.toLowerCase()) ||
      product.description.toLowerCase().includes(filterText.toLowerCase())
  ) : [];
   const sortedProducts = filteredProducts.sort((a, b) => {
    if (a[sortColumn] < b[sortColumn]) return sortDirection === "asc" ? -1 : 1;
    if (a[sortColumn] > b[sortColumn]) return sortDirection === "asc" ? 1 : -1;
    return 0;
  });

  console.log(sortedProducts)
  return (
    <div className="flex flex-col h-full w-full">
      <header className="bg-muted/40 p-4 flex items-center justify-between">
        <h1 className="text-2xl font-bold">Products</h1>
        <div className="flex items-center gap-4">
          <Input
            type="text"
            placeholder="Search products..."
            value={filterText}
            onChange={handleFilter}
            className="bg-background px-4 py-2 rounded-md shadow-sm"
          />
          <Button size="sm" variant="outline">
            Add Product
          </Button>
        </div>
      </header>
      <div className="flex-1 overflow-auto p-4">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="cursor-pointer">
                Img{" "}
              </TableHead>
              <TableHead className="cursor-pointer" onClick={() => handleSort("name")}>
                Name{" "}
                {sortColumn === "name" && (
                  <span className="text-muted-foreground">{sortDirection === "asc" ? "\u2191" : "\u2193"}</span>
                )}
              </TableHead>
              <TableHead className="cursor-pointer" onClick={() => handleSort("description")}>
                Description{" "}
                {sortColumn === "description" && (
                  <span className="text-muted-foreground">{sortDirection === "asc" ? "\u2191" : "\u2193"}</span>
                )}
              </TableHead>
              <TableHead className="cursor-pointer" onClick={() => handleSort("price")}>
                Price{" "}
                {sortColumn === "price" && (
                  <span className="text-muted-foreground">{sortDirection === "asc" ? "\u2191" : "\u2193"}</span>
                )}
              </TableHead>
              <TableHead className="cursor-pointer" onClick={() => handleSort("stock")}>
                Stock{" "}
                {sortColumn === "stock" && (
                  <span className="text-muted-foreground">{sortDirection === "asc" ? "\u2191" : "\u2193"}</span>
                )}
              </TableHead>
              <TableHead>Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {sortedProducts.map((product) => (
              <TableRow key={product.id}>
                <TableCell className="font-medium">{product.img}</TableCell>
                <TableCell className="font-medium">{product.name}</TableCell>
                <TableCell>{product.description}</TableCell>
                <TableCell>${product.price.toFixed(2)}</TableCell>
                <TableCell>{product.stock}</TableCell>
                <TableCell>
                  <div className="flex items-center gap-2">
                    <Button size="icon" variant="ghost" 
                    
                    >
                      <FilePenIcon className="h-4 w-4" />
                      <span className="sr-only">Edit</span>
                    </Button>
                    <Button size="icon" variant="ghost"onClick={() => handleDelete(product.id)}>
                      <TrashIcon className="h-4 w-4" />
                      <span className="sr-only">Delete</span>
                    </Button>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </div>
  )
}

function FilePenIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 22h6a2 2 0 0 0 2-2V7l-5-5H6a2 2 0 0 0-2 2v10" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
      <path d="M10.4 12.6a2 2 0 1 1 3 3L8 21l-4 1 1-4Z" />
    </svg>
  )
}


function TrashIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>
  )
}
